In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [2]:
zeros_arr = np.zeros((2,3))
ones_arr = np.ones((3,2))
#zeros_arr
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
random_arr = np.random.rand(2,3)
random_arr

array([[0.05768857, 0.73730848, 0.58643732],
       [0.35875772, 0.62533527, 0.2798314 ]])

In [4]:
arr1 = np.random.rand(3,3)*9+1



NameError: name 'rand' is not defined

In [6]:
arr = np.array([1,2,3,4,5])
sliced_arr = arr[1:4]
#sliced_arr[0]
sliced_arr

array([2, 3, 4])

In [9]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
arr = np.array([[1,2,0],[3,4,5],[6,7,8]])
arr

array([[1, 2, 0],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,0:2]

array([1, 2])

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [17]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr[0:2,0:2,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [18]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr[1:2,0:1,0:2]

array([[[10, 11]]])

In [23]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [27]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
arr[1,1,2]

15

In [30]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
arr[0:,1,0:2]

array([[ 4,  5],
       [13, 14],
       [22, 23]])

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr_view = arr.view()
arr_copy = arr.copy()

